import {
  DollarOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  FileProtectOutlined,
  DatabaseOutlined,
  BoldOutlined,
  ShoppingCartOutlined,
} from "@ant-design/icons";

const cardData = [
  {
    id: 1,
    title: "Earning",
    amount: "$194K",
    percentChange: "32.2%",
    timeFrame: "this month",
    icon: <DollarOutlined />,
    percentChangeIcon: <ArrowUpOutlined />,
    iconStyle: "Icon1",
    icon_container: "icon_container1",
    icon_and_info: "icon_and_info",
    icon_color: "icon_color1",
  },
  {
    id: 2,
    title: "Orders",
    amount: "$2.4K",
    percentChange: "2%",
    timeFrame: "this month",
    icon: <FileProtectOutlined />,
    percentChangeIcon: <ArrowDownOutlined />,
    iconStyle: "Icon2",
    icon_container: "icon_container2",
    icon_and_info: "icon_and_info",
    icon_color: "icon_color2",
  },
  {
    id: 3,
    title: "Balance",
    amount: "$2.4K",
    percentChange: "2%",
    timeFrame: "this month",
    icon: <DatabaseOutlined />,
    percentChangeIcon: <ArrowDownOutlined />,
    iconStyle: "Icon3",
    icon_container: "icon_container3",
    icon_and_info: "icon_and_info",
    icon_color: "icon_color2",
  },
  {
    id: 1,
    title: "Total Sales",
    amount: "$89K",
    percentChange: "11%",
    timeFrame: "this week",
    icon: <ShoppingCartOutlined />,
    percentChangeIcon: <ArrowUpOutlined />,
    iconStyle: "Icon4",
    icon_container: "icon_container4",
    icon_and_info: "icon_and_info",
    icon_color: "icon_color1",
  },
];

export default cardData;
